-- Create the Images Table
CREATE TABLE IF NOT EXISTS images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    image_url TEXT NOT NULL
);

-- Create the Questions Table
CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    image_id BIGINT REFERENCES images(id) ON DELETE CASCADE NOT NULL,
    question_text TEXT NOT NULL,
    options TEXT[] NOT NULL,
    correct_option TEXT NOT NULL
);

-- FIX: Clears out old tests and forces auto-incrementing IDs to start back at 1
TRUNCATE TABLE questions, images RESTART IDENTITY CASCADE;

-- Insert local filenames into the Images Table (IDs 1, 2, 3, 4 will be auto-generated)
INSERT INTO images (image_url) VALUES 
('obs1.jpeg'),
('obs2.jpg'),
('obs3.jpeg'),
('obs4.jpeg');

-- =========================================================================
-- QUESTIONS MATRIX FOR IMAGE 1 (obs1.jpeg - Airplane Terminal Layout)
-- =========================================================================
INSERT INTO questions (image_id, question_text, options, correct_option) VALUES 
(1, 'What is written on the side of the main red vehicle near the airplane?', ARRAY['AIRPORT', 'FIRE', 'CATERING', 'SERVICES'], 'CATERING'),
(1, 'What color is the striped warning pattern on the ground safety barrier lines?', ARRAY['Black and White', 'Red and White', 'Yellow and Black', 'Blue and Yellow'], 'Red and White'),
(1, 'How many distinct jet engines are visible mounted underneath the wings of the main aircraft?', ARRAY['1', '2', '4', 'None'], '2'),
(1, 'What color is the jacket worn by the ground crew member standing closest to the front nose gear?', ARRAY['Neon Green', 'Bright Orange', 'Deep Blue', 'High-Vis Yellow'], 'Bright Orange');

-- =========================================================================
-- QUESTIONS MATRIX FOR IMAGE 2 (obs2.jpg - Science Lab Classroom)
-- =========================================================================
INSERT INTO questions (image_id, question_text, options, correct_option) VALUES 
(2, 'What object is prominently sitting on top of the small wooden stool in the foreground?', ARRAY['A Microscope', 'A Glass Beaker', 'An Open Book', 'A Globe'], 'A Glass Beaker'),
(2, 'What structure or illustration is drawn on the leftmost section of the dark blackboard?', ARRAY['A Chemical Element Chart', 'A Geometric Triangle', 'A Human Skeleton Outline', 'A Plant Cell Diagram'], 'A Geometric Triangle'),
(2, 'How many hanging glass pendant light fixtures are suspended from the ceiling beams?', ARRAY['2', '3', '4', '5'], '3'),
(2, 'What is the color of the large cabinet doors standing along the back right wall?', ARRAY['Dark Green', 'Natural Wood Brown', 'Charcoal Gray', 'Muted Teal'], 'Natural Wood Brown');

-- =========================================================================
-- QUESTIONS MATRIX FOR IMAGE 3 (obs3.jpeg - Modern Living Room)
-- =========================================================================
INSERT INTO questions (image_id, question_text, options, correct_option) VALUES 
(3, 'What item is placed directly on the lower shelf of the round coffee table?', ARRAY['A Stack of Books', 'A Small Potted Plant', 'A Ceramic Bowl', 'A Scented Candle'], 'A Stack of Books'),
(3, 'How many round decorative throw pillows are placed on the main cream-colored sofa?', ARRAY['2', '3', '4', '5'], '3'),
(3, 'What color is the large abstract canvas artwork hanging on the central wall?', ARRAY['Black and White Monochromatic', 'Blue, Orange, and Gold', 'Solid Crimson Red', 'Pastel Pink and Green'], 'Blue, Orange, and Gold'),
(3, 'What type of light fixture is positioned directly next to the accent armchair?', ARRAY['A Black Floor Lamp', 'A Golden Wall Sconce', 'A Crystal Chandelier', 'A Table Desk Lamp'], 'A Black Floor Lamp');

-- =========================================================================
-- QUESTIONS MATRIX FOR IMAGE 4 (obs4.jpeg - Pixel Art Arcade)
-- =========================================================================
INSERT INTO questions (image_id, question_text, options, correct_option) VALUES 
(4, 'What graphic icon or text is displayed on the glowing neon sign at the top center?', ARRAY['ARCADE', 'OPEN', 'GAME OVER', 'A Glowing Joystick Pixel'], 'ARCADE'),
(4, 'What color is the outer cabinet chassis of the arcade machine sitting on the far right?', ARRAY['Neon Pink', 'Electric Blue', 'Bright Yellow', 'Deep Purple'], 'Bright Yellow'),
(4, 'Which character or item sprite is clearly visible on the screen of the center monitor?', ARRAY['A Spaceship', 'A Yellow Pacman', 'A Pixelated Ghost', 'A Jumping Plumber'], 'A Spaceship'),
(4, 'How many individual bar stools are placed lined up in front of the counter layout?', ARRAY['2', '3', '4', 'None'], '3');


-- Enable Row Level Security on both tables (Good practice)
ALTER TABLE images ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows completely public READ access to the tables
CREATE POLICY "Allow public read access for images" 
ON images FOR SELECT 
TO anon 
USING (true);

CREATE POLICY "Allow public read access for questions" 
ON questions FOR SELECT 
TO anon 
USING (true);
