name: Secret Scanning

on:
  push:
    branches: [ "Main", "main", "master" ]
  pull_request:
    branches: [ "Main", "main", "master" ]

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog Secret Scanner
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --debug --only-verified
