name: Sync Labels

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/labels.yml"

permissions:
  issues: write
  pull-requests: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Sync repository labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          delete-other-labels: false
          token: ${{ secrets.GITHUB_TOKEN }}
