name: Update Contributors in README

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update-readme:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Contributors
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          readme_path: "README.md"
          commit_message: "docs(readme): auto-update contributor list [skip ci]"